'use client'
import * as React from 'react'
import { motion, useReducedMotion } from 'framer-motion'
import { LogoMark } from '@/components/brand/Logo'
import { AssembleMark } from '@/components/landing/AssembleMark'
import { Section } from '@/components/landing/Section'
import { cn } from '@/lib/utils/format'

/**
 * Community Compute Diagram: Lazarus Core at the centre, six connected nodes
 * with animated lines. Hover/focus reveals a compact explanation card. Below
 * `md` the diagram becomes a vertical animated flow.
 */
const NODES = [
  { id: 'fees', label: 'Protocol Fees', blurb: 'Fees generated by trading activity on the protocol.' },
  { id: 'treasury', label: 'Compute Treasury', blurb: 'Protocol revenue allocated to GPU infrastructure and compute providers.' },
  { id: 'gpu', label: 'GPU Pool', blurb: 'Active capacity available to run inference jobs.' },
  { id: 'models', label: 'Model Registry', blurb: 'Open-weight models served through the network, health-checked against the provider.' },
  { id: 'credits', label: 'Holder Credits', blurb: 'Token holders receive compute credits according to protocol rules.' },
  { id: 'revenue', label: 'Usage Revenue', blurb: 'Paid external usage that flows back into the Lazarus ecosystem.' },
]

const W = 760, H = 460, CX = W / 2, CY = H / 2, RX = 300, RY = 170

export function ComputeDiagram() {
  const [active, setActive] = React.useState<string | null>(null)
  const reduce = useReducedMotion()
  const pos = NODES.map((_, i) => {
    const a = -Math.PI / 2 + (i / NODES.length) * Math.PI * 2
    return { x: CX + Math.cos(a) * RX, y: CY + Math.sin(a) * RY }
  })
  const current = NODES.find((n) => n.id === active)

  return (
    <Section id="network" eyebrow="Network" title="Community compute, connected." lead="Every node is a real subsystem of the application. Hover a node to see what it does.">
      {/* Desktop / tablet */}
      <div className="card relative hidden overflow-hidden p-6 md:block">
        <div className="grid-bg absolute inset-0 opacity-50" aria-hidden />
        <svg viewBox={`0 0 ${W} ${H}`} className="relative w-full" role="img" aria-label="Lazarus compute network diagram">
          {pos.map((p, i) => {
            const q = pos[(i + 1) % pos.length]
            return (
              <g key={i}>
                <line x1={CX} y1={CY} x2={p.x} y2={p.y} stroke="rgb(var(--line))" strokeOpacity="0.12" strokeWidth="1" />
                <line x1={p.x} y1={p.y} x2={q.x} y2={q.y} stroke="#D92989" strokeOpacity={active ? 0.25 : 0.45} strokeWidth="1" strokeDasharray="3 6" className={reduce ? undefined : 'animate-dash-flow'} style={{ animationDuration: `${6 + i}s` }} />
              </g>
            )
          })}
          {!reduce &&
            pos.map((p, i) => {
              const q = pos[(i + 1) % pos.length]
              return (
                <motion.circle key={`pulse-${i}`} r="3" fill="#F13CA6" initial={{ cx: p.x, cy: p.y, opacity: 0 }} animate={{ cx: [p.x, q.x], cy: [p.y, q.y], opacity: [0, 1, 1, 0] }} transition={{ duration: 3.2, delay: i * 1.5, repeat: Infinity, repeatDelay: NODES.length * 1.5 - 3.2, ease: 'linear' }} />
              )
            })}
          <g>
            <circle cx={CX} cy={CY} r="58" fill="rgb(var(--surface))" stroke="var(--border-strong)" />
            <circle cx={CX} cy={CY} r="70" fill="none" stroke="#D92989" strokeOpacity="0.35" strokeDasharray="2 5" className={reduce ? undefined : 'animate-dash-flow'} style={{ animationDuration: '14s' }} />
            <foreignObject x={CX - 26} y={CY - 26} width="52" height="52">
              <AssembleMark size={52} />
            </foreignObject>
            <text x={CX} y={CY + 92} textAnchor="middle" className="fill-[rgb(var(--ink))]" style={{ fontSize: 11, fontFamily: 'var(--font-mono)', letterSpacing: '0.16em' }}>
              LAZARUS CORE
            </text>
          </g>
          {NODES.map((n, i) => {
            const p = pos[i]
            const isActive = active === n.id
            return (
              <g key={n.id} tabIndex={0} role="button" aria-label={n.label} className="cursor-pointer outline-none" onMouseEnter={() => setActive(n.id)} onMouseLeave={() => setActive(null)} onFocus={() => setActive(n.id)} onBlur={() => setActive(null)}>
                <motion.g animate={reduce ? undefined : { y: [0, -4, 0] }} transition={{ duration: 6 + i * 0.7, repeat: Infinity, ease: 'easeInOut' }}>
                  <polygon points={`${p.x},${p.y - 11} ${p.x + 11},${p.y} ${p.x},${p.y + 11} ${p.x - 11},${p.y}`} fill={isActive ? '#D92989' : 'rgb(var(--surface))'} stroke="#D92989" strokeWidth="1.2" />
                  <rect x={p.x - 62} y={p.y + 18} width="124" height="24" rx="6" fill="rgb(var(--surface))" stroke={isActive ? '#D92989' : 'var(--border-strong)'} />
                  <text x={p.x} y={p.y + 34} textAnchor="middle" className="fill-[rgb(var(--ink))]" style={{ fontSize: 11.5, fontFamily: 'var(--font-sans)', fontWeight: 500 }}>
                    {n.label}
                  </text>
                </motion.g>
              </g>
            )
          })}
        </svg>
        <div className={cn('pointer-events-none absolute bottom-6 left-6 max-w-xs rounded-lg border bg-surface p-4 text-sm shadow-pop transition-opacity duration-300', current ? 'opacity-100' : 'opacity-0')} style={{ borderColor: 'var(--border-strong)' }} aria-live="polite">
          <div className="text-[13px] font-semibold">{current?.label ?? ''}</div>
          <p className="mt-1 text-xs leading-relaxed text-muted">{current?.blurb ?? ''}</p>
        </div>
      </div>

      {/* Mobile: vertical flow */}
      <ol className="relative flex flex-col gap-3 md:hidden">
        <li className="card flex items-center gap-3 p-4">
          <LogoMark size={36} />
          <div>
            <div className="font-mono text-[11px] tracking-[0.16em]">LAZARUS CORE</div>
            <div className="text-xs text-muted">Protocol coordination layer</div>
          </div>
        </li>
        {NODES.map((n, i) => (
          <motion.li key={n.id} initial={reduce ? false : { opacity: 0, x: -10 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ duration: 0.6, delay: i * 0.08 }} className="relative pl-6">
            <span className="absolute left-[7px] top-0 h-full w-px bg-magenta/40" aria-hidden />
            <span className="absolute left-0 top-5 h-[15px] w-[15px] rotate-45 border border-magenta bg-surface" aria-hidden />
            <div className="card p-4">
              <div className="text-sm font-semibold">{n.label}</div>
              <p className="mt-1 text-xs leading-relaxed text-muted">{n.blurb}</p>
            </div>
          </motion.li>
        ))}
      </ol>
    </Section>
  )
}
