#!/usr/bin/env node
/**
 * Vectorises the Lazarus mark from public/brand/lazarus-logo.jpg.
 *
 * The raster is ten magenta polygons separated by black gaps. Each coloured
 * connected component is traced (convex hull → simplified to its corners) and
 * written to src/config/logo-geometry.ts in unit coordinates, together with
 * its mean colour, so <LogoMark/> and the landing visuals share the exact
 * geometry of the supplied logo. Run:  node scripts/make-logo.mjs [--render out.png]
 */
import { writeFileSync } from 'node:fs'

const sharp = (await import(process.env.SHARP_PATH || 'sharp')).default
const SRC = 'public/brand/lazarus-logo.jpg'
const { data, info } = await sharp(SRC).raw().toBuffer({ resolveWithObject: true })
const W = info.width, H = info.height
const lum = (i) => data[i * 3] * 0.5 + data[i * 3 + 1] * 0.25 + data[i * 3 + 2] * 0.25
const on = new Uint8Array(W * H)
for (let i = 0; i < W * H; i++) on[i] = lum(i) > 45 ? 1 : 0

// Connected components (4-neighbour flood fill).
const label = new Int32Array(W * H).fill(-1)
const comps = []
const stack = new Int32Array(W * H)
for (let s = 0; s < W * H; s++) {
  if (!on[s] || label[s] !== -1) continue
  const id = comps.length
  const pts = []
  let sp = 0
  stack[sp++] = s
  label[s] = id
  let r = 0, g = 0, b = 0
  while (sp) {
    const i = stack[--sp]
    const x = i % W, y = (i - x) / W
    pts.push([x, y])
    r += data[i * 3]; g += data[i * 3 + 1]; b += data[i * 3 + 2]
    for (const j of [i - 1, i + 1, i - W, i + W]) {
      if (j < 0 || j >= W * H) continue
      if ((j === i - 1 && x === 0) || (j === i + 1 && x === W - 1)) continue
      if (on[j] && label[j] === -1) { label[j] = id; stack[sp++] = j }
    }
  }
  const n = pts.length
  comps.push({ pts, n, color: [r / n, g / n, b / n] })
}
const big = comps.filter((c) => c.n > 400 && c.color[0] - c.color[1] > 40).sort((a, b) => b.n - a.n)
console.log(`${comps.length} components, ${big.length} faces`)

function hull(points) {
  const p = points.slice().sort((a, b) => a[0] - b[0] || a[1] - b[1])
  const cross = (o, a, b) => (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0])
  const lower = []
  for (const q of p) { while (lower.length >= 2 && cross(lower[lower.length - 2], lower[lower.length - 1], q) <= 0) lower.pop(); lower.push(q) }
  const upper = []
  for (let i = p.length - 1; i >= 0; i--) { const q = p[i]; while (upper.length >= 2 && cross(upper[upper.length - 2], upper[upper.length - 1], q) <= 0) upper.pop(); upper.push(q) }
  return lower.slice(0, -1).concat(upper.slice(0, -1))
}
function area(poly) {
  let a = 0
  for (let i = 0; i < poly.length; i++) { const p = poly[i], q = poly[(i + 1) % poly.length]; a += p[0] * q[1] - q[0] * p[1] }
  return Math.abs(a) / 2
}
/** Remove hull vertices whose removal changes the area least, until only true corners remain. */
function simplify(poly) {
  const full = area(poly)
  let cur = poly.slice()
  while (cur.length > 3) {
    let bestI = -1, bestLoss = Infinity
    for (let i = 0; i < cur.length; i++) {
      const test = cur.filter((_, k) => k !== i)
      const loss = Math.abs(area(test) - full)
      if (loss < bestLoss) { bestLoss = loss; bestI = i }
    }
    if (bestLoss > Math.max(full * 0.02, 400)) break
    cur = cur.filter((_, k) => k !== bestI)
  }
  return cur
}

// Frame: bounding box of all faces, padded to a square so the mark centres cleanly.
let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity
for (const c of big) for (const [x, y] of c.pts) { if (x < minX) minX = x; if (x > maxX) maxX = x; if (y < minY) minY = y; if (y > maxY) maxY = y }
const cx = (minX + maxX) / 2, cy = (minY + maxY) / 2
const R = Math.max(maxX - minX, maxY - minY) / 2
const hex = (c) => '#' + c.map((v) => Math.round(v).toString(16).padStart(2, '0')).join('')
const faces = big.map((c) => {
  const poly = simplify(hull(c.pts))
  const points = poly.map(([x, y]) => [Math.round(((x - cx) / R) * 1000) / 1000, Math.round(((y - cy) / R) * 1000) / 1000])
  const brightness = c.color[0] + c.color[1] + c.color[2]
  return { points, color: hex(c.color), area: Math.round((area(poly) / (R * R)) * 1000) / 1000, brightness }
})
// Three tones, ranked by brightness: 1 core, 3 inner, rest rim.
faces.sort((a, b) => b.brightness - a.brightness)
const out = faces.map((f, i) => ({ tone: i === 0 ? 'core' : i < 4 ? 'inner' : 'rim', points: f.points, color: f.color, area: f.area }))
for (const f of out) console.log(f.tone.padEnd(6), f.color, f.points.length, 'pts', 'area', f.area)

const ts = `// Generated by scripts/make-logo.mjs from public/brand/lazarus-logo.jpg — do not edit by hand.
// Unit-square coordinates (x right, y down, range −1..1) of the ten faces of the Lazarus mark.
export type LogoTone = 'core' | 'inner' | 'rim'
export interface LogoFace { tone: LogoTone; points: [number, number][]; color: string; area: number }
export const LOGO_FACES: LogoFace[] = ${JSON.stringify(out)}
`
writeFileSync('src/config/logo-geometry.ts', ts)
console.log('wrote src/config/logo-geometry.ts')

if (process.argv.includes('--render')) {
  const S = 1078, CX = S / 2, CY = S / 2, RR = R
  const polys = out.map((f) => `<polygon points="${f.points.map(([x, y]) => `${CX + x * RR},${CY + y * RR}`).join(' ')}" fill="${f.color}"/>`).join('')
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${S}" height="${S}"><rect width="${S}" height="${S}" fill="#000"/>${polys}</svg>`
  await sharp(Buffer.from(svg)).png().toFile(process.argv[process.argv.indexOf('--render') + 1] || 'logo-render.png')
  console.log('rendered')
}
